### ISSUE TITLE
Add support for void elements

### ISSUE THREAD

**Issue by hibachrach** [lpil/htmb#1]
In HTML5, elements like `br` [do not have a closing tag](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements)--right now `htmb.h` only supports elements which have both an opening and closing tag.

**Comment by lpil** [comment]
Being able to render these sounds good! What should the design be? A different function? A list of names that we render the void syntax for? If the latter would the programmer ever need to be able to render a void tag for other elements? Perhaps web components? I'm not familiar with their requirements.

Lots of questions, sorry 😁

**Comment by hibachrach** [comment]
It depends!

If we're just targeting HTML5, this is a complete list of all of the void elements ([source](https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#syntax-elements)):
> [area](https://www.w3.org/TR/2011/WD-html-markup-20110113/area.html#area), [base](https://www.w3.org/TR/2011/WD-html-markup-20110113/base.html#base), [br](https://www.w3.org/TR/2011/WD-html-markup-20110113/br.html#br), [col](https://www.w3.org/TR/2011/WD-html-markup-20110113/col.html#col), [command](https://www.w3.org/TR/2011/WD-html-markup-20110113/command.html#command), [embed](https://www.w3.org/TR/2011/WD-html-markup-20110113/embed.html#embed), [hr](https://www.w3.org/TR/2011/WD-html-markup-20110113/hr.html#hr), [img](https://www.w3.org/TR/2011/WD-html-markup-20110113/img.html#img), [input](https://www.w3.org/TR/2011/WD-html-markup-20110113/input.html#input), [keygen](https://www.w3.org/TR/2011/WD-html-markup-20110113/keygen.html#keygen), [link](https://www.w3.org/TR/2011/WD-html-markup-20110113/link.html#link), [meta](https://www.w3.org/TR/2011/WD-html-markup-20110113/meta.html#meta), [param](https://www.w3.org/TR/2011/WD-html-markup-20110113/param.html#param), [source](https://www.w3.org/TR/2011/WD-html-markup-20110113/source.html#source), [track](https://www.w3.org/TR/2011/WD-html-markup-20110113/track.html#track), [wbr](https://www.w3.org/TR/2011/WD-html-markup-20110113/wbr.html#wbr)

So we can just check if the element is one of them. Custom elements cannot be void, per the spec.

If the package is intended to be able to output valid XML (or similar langs like JSX, XHTML, SVG, or MathML) then we need to think about "self-closing elements" like `<foo />`. In that case, I'm not sure! We have a few options
* A `self_closing` optional param which defaults to false (if https://github.com/gleam-lang/gleam/discussions/1122 turns into a PR)
* A separate fn for self-closing elements
* Separate fns for HTML5 vs XML-inspired languages (afaik, `<foo></foo>` and `<foo />` are equivalent in all XML-inspired languages, though I am not 100% certain) and just output a self-closing element if there are no children given. This option makes the most sense to me assuming that is correct

**Comment by lpil** [comment]
I'm tempted to say only html5, but if we do this then we should probably also change the render_page function to be hard-coded to the html5 doctype, and document that this library is only for html5.

**Comment by hibachrach** [comment]
I think that's fine--in the case of SVG and MathML (which can both be embedded in HTML), an opening and closing tag should be equivalent with the self-closing form (https://html.spec.whatwg.org/multipage/syntax.html#elements-2).

One could easily fork this package if they wanted to make something to target XML or JSX specifically (though even there, self-closing tags may suffice too).

**Comment by hibachrach** [comment]
Would you be open to a PR? This would be my first opportunity to actually write some non-playground Gleam 😄

**Comment by lpil** [comment]
Yes please!

**Comment by hibachrach** [comment]
Opened! See #2
